
import "./globals.css";

export const metadata = {
	title: "Waste2Plate",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
      <body className="antialiased">
			</body>
		</html>
	);
}
